### ISSUE TITLE
multi-metric packets are not formatted correctly

### ISSUE THREAD

**Issue by gmlevin** [jsocol/pystatsd#100]
I am seeing that if there are multiple metrics showing up in a udp packet, they are not separated by newlines, per this reference.

https://github.com/etsy/statsd/blob/master/docs/metric_types.md#multi-metric-packets

I am seeing things like `X:100|gY:250|g` which is misinterpreted by the daemon.
Is this configurable? Is there a work around?

**Comment by gmlevin** [comment]
I am working in Python3 with asycio. I am wondering if it is a threading issue. Doing more testing and will get back.

**Comment by gmlevin** [comment]
My problem. Using socat to get packets out of a docker container and it is appending them.

**Comment by jsocol** [comment]
That was gonna be my question, glad you figured it out!
