### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Connection'

### ISSUE THREAD

**Issue by onlineexamsystem** [jsocol/pystatsd#101]
i was following the example given here https://pypi.python.org/pypi/python-statsd under the advanced section.

```
import statsd
conn = statsd.Connection(host='metrics.test.com',port=2000)
```
this is giving me following error

```
conn = statsd.Connection(host='metrics.test.com',port=2000)
AttributeError: 'module' object has no attribute 'Connection'
```

can anybody explain what the issue is ?

**Comment by jsocol** [comment]
This is a different package: https://pypi.python.org/pypi/statsd. If you installed `pip install python-statsd`, you'll need to follow their docs. If you did `pip install statsd` you'll end up here.

**Comment by onlineexamsystem** [comment]
@jsocol Thanks . i missed that.
one more question. while reading the documentation here http://statsd.readthedocs.io/en/v3.2.1/types.html  i didn't find any way to send just raw data .
is there any way on how to do it ?
