### ISSUE TITLE
3.2.2 is not published yet

### ISSUE THREAD

**Issue by patoroco** [jsocol/pystatsd#103]
Hi,

I was reading [CHANGES](https://github.com/jsocol/pystatsd/blob/c934453f8d5709f7075b845e03ba31e228d31bca/CHANGES#L9) file, and it shows reference to 3.2.2 version, which was done in https://github.com/jsocol/pystatsd/commit/7c5ccf18c916ad4b812668c5f63170f9bb8b02a2, but this is not published yet in pypi.

Could you push it to use these version instead of use github+sha reference?

Thanks!

**Comment by jsocol** [comment]
Oops, done! Thanks for pointing it out. https://pypi.python.org/pypi/statsd/3.2.2
