### ISSUE TITLE
Incorrect metrics for coroutine functions.

### ISSUE THREAD

**Issue by nkonin** [jsocol/pystatsd#119]
Code example:
```python
In [1]: import asyncio
   ...: from statsd import StatsClient
   ...:
   ...: sc = StatsClient()
   ...:
   ...: @sc.timer("foo")
   ...: async def f():
   ...:     return await asyncio.sleep(2)
   ...:
   ...:

In [2]: %time asyncio.get_event_loop().run_until_complete(f())  # IPython %time command
   ...:
CPU times: user 917 µs, sys: 1.22 ms, total: 2.14 ms
Wall time: 2 s
```
Expected behavior:
~ 2000ms sent to statsd server
Current behavior:
~ 0.001ms sent to statsd server

I believe the reason of this behavior – this part of code:
https://github.com/jsocol/pystatsd/blob/100046bcd349013d6d78922585621159a33d1ebb/statsd/client/timer.py#L36-L41

There is no awaiting for coroutine, so there is no real work in metric.

It's seems like solution should be something like (but with with backward compatibility support):

```python
from inspect import iscoroutinefunction

# ...

def __call__(self, f):
        """Thread-safe timing function decorator."""

    if iscoroutinefunction(f):
        @safe_wraps(f)
        async def _wrapped(*args, **kwargs):
            start_time = time_now()
            try:
                return await f(*args, **kwargs)
            finally:
                elapsed_time_ms = 1000.0 * (time_now() - start_time)
                self.client.timing(self.stat, elapsed_time_ms, self.rate)
    
    else:
        @safe_wraps(f)
        def _wrapped(*args, **kwargs):
            start_time = time_now()
            try:
                return f(*args, **kwargs)
            finally:
                elapsed_time_ms = 1000.0 * (time_now() - start_time)
                self.client.timing(self.stat, elapsed_time_ms, self.rate)
    return _wrapped
```

**Comment by jsocol** [comment]
Oh interesting. This code will run in Python 2.7 or 3.4? I thought it would be a syntax error since `async` and `await` were new keywords.

**Comment by nkonin** [comment]
The code above is just a draft for a possible solution.
At the moment there will be `ImportError`, since` iscoroutinefunction` appears only in python3.5 +

If you think it's ok as concept, I can do PR with backwards compatibility for older python versions on the weekend.

**Comment by jsocol** [comment]
I'm actually not sold on this being the right approach. I think in #93 we talked through the implications of including an `async` function in this library and it wasn't a viable path forward because it causes a `SyntaxError` in python 2.7—and starts us down a path of doubling the API surface area (again). There is a library, [aiomeasures](https://pypi.org/project/aiomeasures/), that may do what you need?

**Comment by nkonin** [comment]
#93 has a different goal. It’s about async client. This issue is about measuring the time of coroutine functions being done. This way we don’t have to double the public API, as for #93 because we’ll have to rewrite only 1 internal method. I suppose here we can use the `@asyncio.coroutine` instead of `async` keyword.

P.S. aiomeasures has the same issue, and the package hasn’t been updated for 3 yrs.

**Comment by jsocol** [comment]
Hmm, well, I'm open to the addition if it works in Py 2.7 and 3.4—which are still supported here.

**Comment by jsocol** [comment]
Whelp, this took me several years but your solution works perfectly:

```python
In [1]: import asyncio
In [2]: from statsd import StatsClient
In [3]: sc = StatsClient()

In [4]: @sc.timer('foo')
   ...: async def f():
   ...:     return await asyncio.sleep(2)

In [12]: sc._send = lambda *a: print(a)

In [13]: await f()
('foo:2001.232375|ms',)
```

Getting a test to prove it was a little trickier, but [this solution](https://jacobbridges.github.io/post/unit-testing-with-asyncio/) worked! Applying this in #172.
