### ISSUE TITLE
Version 3.3.0 breaks backward compatibility

### ISSUE THREAD

**Issue by jancespivo** [jsocol/pystatsd#120]
Hi,
we use typings in our projects. And because we want to run our projects on variety of clients according to actual demands (for example UnixSocketStatsClient  or TCPStatsClient or StatsClient) we use supertype `statsd.client.StatsClientBase` for typings. Unfortunatelly the `StatsClientBase` has been moved to `statsd.client.base` so the code is broken now. We know it is undocumented API, but it is public class.

I created the pull request for it: https://github.com/jsocol/pystatsd/pull/121

Best regards

**Comment by jsocol** [comment]
You’re correct that this isn’t a public API or intended extension point. I’m not inclined to “fix” this, since I don’t really think it’s broken. Using private APIs inherently comes with this risk, and I’d suggest updating the code that’s pointing to the base class.
