### ISSUE TITLE
Support for AF_UNIX sockets?

### ISSUE THREAD

**Issue by lorencarvalho** [jsocol/pystatsd#127]
Hi there!

I'm a big fan of this library and have used it extensively! I have a use case where I need to emit from many services on a box to a single statsd daemon (also on the box) that is listening on an AF_UNIX socket. To accomplish this I've subclassed the StatsClientBase in this library and added support for emitting to an AF_UNIX socket.

I'm happy to submit a patch based on the subclass I mention, but I wanted to ask first if you would be interested in one. And if so, would you prefer it be "automatic" e.g. in my subclass if the `port` parameter is `None` we assume that the `address` is AF_UNIX. To me, that seems a little magical compared to the pystatsd API which is very explicit (and nice!). If so, would you prefer it be it's own StatsClientBase subclass like `StatsClientLocal` or something like that?

**Comment by jsocol** [comment]
Hi, thanks for the support and the issue!

I wasn’t aware that the StatsD server even supported Unix sockets—is it a different project?

I’m not super familiar with Unix sockets but do they behave like datagrams or like a stream?

**Comment by jsocol** [comment]
I thought this sounded familiar: does the existing [UnixSocketStatsClient](https://statsd.readthedocs.io/en/v3.2.1/unix_socket.html) not work?

**Comment by lorencarvalho** [comment]
Ha! Wow, can't believe I missed that. Perfect!

**Comment by jsocol** [comment]
See https://github.com/jsocol/pystatsd/pull/128#issuecomment-511463750
