### ISSUE TITLE
How to push text data ?

### ISSUE THREAD

**Issue by Sriram21** [jsocol/pystatsd#143]
Hi,
Is it possible to push textual data to statsd listeners..

for eg mysql_version : "v8.9"
          interface_name: "e1"

Regards,
Sriram

**Comment by jsocol** [comment]
Hey @Sriram21, to clarify, are you thinking about metadata associated with a metric, like [Datadog's tags](https://docs.datadoghq.com/getting_started/tagging/)? Or a metric like `mysql_version` that has distinct, non-numeric values like a [set](https://github.com/statsd/statsd/blob/master/docs/metric_types.md#sets)?

**Comment by Sriram21** [comment]
Hi @jsocol ,

I am asking in the context of metadata assosciated for an application.. For eg if metrics are collected for mysql application numerical values such as connection count , open file count will go under gauge metric type.. Similary for non-numeric values ( metadata ) such as mysql-version how do we push it ? There are no metric types assoscciated with it.

Regards,
Sriram

**Comment by jsocol** [comment]
Ah thanks for clarifying. Statsd isn’t meant to store that kind of metadata. It’s designed to aggregate numeric metrics. 

There are a couple of things like statsd, like DataDog and Telegraf, that have extended the statsd protocol with “tags”, which allow arbitrary metadata on _each metric_ to allow you to disaggregate and slice the data. For example you could tag each connection open counter with the MySQL client and server versions. But statsd itself—and this client—don’t support that extension.
