### ISSUE TITLE
Version switcher in online documentation does not work in v3.2.2 and earlier

### ISSUE THREAD

**Issue by daniel-dara** [jsocol/pystatsd#144]
If you visit the [online documentation](https://statsd.readthedocs.io), there is a dropdown in the lower left for switching versions. If you switch to v3.2.2 or earlier, then the dropdown no longer works (clicking on it does nothing as opposed to opening the list of versions again).

The following javascript error appears in the console when switching to a version where the switcher is broken. Perhaps it is related.
```
(index):412 Uncaught ReferenceError: SphinxRtdTheme is not defined
    at HTMLDocument.<anonymous> ((index):412)
    at f (jquery-2.0.3.min.js:23)
    at Object.fireWith [as resolveWith] (jquery-2.0.3.min.js:23)
    at Function.ready (jquery-2.0.3.min.js:22)
    at HTMLDocument.dt (jquery-2.0.3.min.js:22)
```

**Comment by jsocol** [comment]
Thanks for the flag! I had to reconnect the webhook from Github to readthedocs. And I've cleaned up which versions are actively built, and triggered rebuilds for all the active docs versions (3.3 and 4.0.1) to make sure that's reflected in the switcher. It should all be fixed up within a few minutes.
