### ISSUE TITLE
Statsd flush interval

### ISSUE THREAD

**Issue by raqib-hayder** [jsocol/pystatsd#153]
I was reading the docs and was confused by the following paragraph. 

> The statsd server collects and aggregates in 30 second intervals before flushing to Graphite. Graphite usually stores the most recent data in 1-minute averaged buckets, so when you’re looking at a graph, for each stat you are typically seeing the average value over that minute.

Does the `30 second` interval here refer to the flush interval? If not, what is the difference between flush interval and 30-second aggregate interval? Do all `statsd` servers aggregate in 30-second intervals? 

P.S. I am using the following [graphite-statsd image](https://hub.docker.com/r/graphiteapp/graphite-statsd/) which has a default flush interval of `10s`.

**Comment by jsocol** [comment]
That is a setting of the statsd server, not this client. Can you link to where that was in the docs?

**Comment by raqib-hayder** [comment]
In the docs, [here](https://statsd.readthedocs.io/en/v3.3/types.html) -> Paragraph 2

**Comment by raqib-hayder** [comment]
Thank you for replying promptly.

**Comment by jsocol** [comment]
Thanks, I’ll add a note there that it’s a default setting. But yeah, it’s the server flush interval behavior, not up to clients.
