### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jlaine** [jsocol/pystatsd#155]
The latest tagged release is version 3.3. Since then there have been a number of commits, would it please be possibly to push out a release based on the current state of the repository?

It might also be the opportunity to fix #132 which just requires a version bump in `__init__.py`.

Thanks!

**Comment by jsocol** [comment]
I'm working on getting this into a better state for v4 now

**Comment by jsocol** [comment]
[Here it is](https://pypi.org/project/statsd/4.0.0/)!
