### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by martinboretto** [jsocol/pystatsd#159]
Hi, 
I'd like to know if the support for Python 3.10 is under your roadmap and, if so, is there any estimated date for this?
Thanks in advance!
Martin

**Comment by jsocol** [comment]
The library itself has supported Python 3.10 this whole time, but the testrunner didn't. I've updated the testrunner for now so that I could get the test suite running on the two latest versions. Longer term I would like to move to only rely on the standard library `unittest` module.
