### ISSUE TITLE
implement pyramid web framework default configuration

### ISSUE THREAD

**Issue by Webinator2129** [jsocol/pystatsd#56]
implement support for pyramid web framework default configuration as done for Django

**Comment by jsocol** [comment]
I'd be happy to look at a pull req for this, but I'm not really familiar with Pyramid, so someone else will need to write the code in `statsd/defaults/pyramid.py`

**Comment by Webinator2129** [comment]
will check with Pyramid team how to best get the settings value

**Comment by jsocol** [comment]
(Still definitely open to a PR that does this, but doing some clean-up.)
