### ISSUE TITLE
Allow lazy loading or re-configuring StatsClient

### ISSUE THREAD

**Issue by tuukkamustonen** [jsocol/pystatsd#62]
Our WSGI application is created something like this:

    def build_app(conf_dir):
        ...
        return app

Here, I cannot define the `StatsClient` inside `build_app` as it wouldn't be importable for decorators then.

So I'm doing something like this:

    class ConfigurableStatsClient(StatsClient):
        """StatsClient extension that allows re-configuration after initialization.

        Implemented because StatsClient does not allow lazy loading.

        """
        def __init__(self, host='localhost', port=8125, prefix=None, maxudpsize=512, enabled=True):
            """Create a new client."""
            super(ConfigurableStatsClient, self).__init__(host, port, prefix, maxudpsize)
            self._enabled = enabled

        def reload(self, host='localhost', port=8125, prefix=None, maxudpsize=512, enabled=True):
            """Reloads client with newly given parameters."""
            self.__init__(host=host, port=port, prefix=prefix, maxudpsize=maxudpsize, enabled=enabled)

        def _send(self, data):
            """Send data to statsd only if client is enabled."""
            if not self._enabled:
                return
            super(ConfigurableStatsClient, self)._send(data)

    STATSD = ConfigurableStatsClient(enabled=False)

    def build_app(conf_dir):

        STATSD.reload(..., enabled=True)

        return app

Actually, `ConfigurableStatsClient` provides to features: 1) allow re-configuring later on, and 2) don't send packets if not `enabled`.

I can make a PR out of this and split it into two, if it makes sense.

Or, would there be some already supported way for doing this?

**Comment by tuukkamustonen** [comment]
Oh great, accidentally clicked Submit button during writing, editing now...

**Comment by jsocol** [comment]
Generally what I would recommend is something like

```python
from statsd.client import StatsClient

_statsd = StatsClient()

def statsd():
    return _statsd

def build_app(conf_dir):
    global _statsd
    _statsd = StatsClient(...)
```

Or with a few more lines of code you could preserve the API:

```python
_statsd = StatsClient()
class StatsProxy(object):
    def __getattr__(self, attr):
        return getattr(_statsd, attr)
statsd = StatsProxy()
```

I'll think about whether it makes sense to upstream something like the above.

One of the things with this type of problem is that it's common-ish, but the solutions are usually too environment specific. Even were it part of the package, many users with similar needs wouldn't be able to use it in their environments, or have already worked around it.

W.r.t. `enabled`, it's the same as the `debug` keyword that's been considered and rejected: since you're making a call site change either way, and it uses UDP and swallows errors, just point to localhost or a non-existent port.

**Comment by tuukkamustonen** [comment]
Thanks for the suggestion, I didn't know I can use proxy objects in decorators. I assume it will do, although you could provide a separate `LazyStatsClient` for lazy people like me, without breaking the api and having to write too many tests?

About `enabled`/`debug`: yeah... but it would still "bloat" the localhost with unnecessary UDP packets. Those might show up in some metrics/statistics tooling then, and give false information, or jump into eyes when you start tracing issues with tcpdump or something like that. As it's just a couple of lines (plus tests), and if others will wonder the same, I'd either support it or just document it. Your call, of course.
