### ISSUE TITLE
Docs: Are timing decorators thread safe or not?

### ISSUE THREAD

**Issue by amedeedaboville** [jsocol/pystatsd#74]
At http://statsd.readthedocs.org/en/latest/timing.html#using-a-decorator it says:

    The timer attribute decorates your methods in a thread-safe manner.

and on http://statsd.readthedocs.org/en/latest/reference.html#timer there is a big yellow warning box that says: 

    Decorators are not thread-safe and may cause errors when decorated functions are called concurrently. Use context managers or raw timers instead.

I'll use a `with` context manager for now, just in case. Thanks for the library!

**Comment by jsocol** [comment]
The thread-safety issue was actually fixed in #50, a while ago. I guess we forgot to remove one of the warnings. Thanks! I'll get to it when I get a chance.

**Comment by jsocol** [comment]
Fixed via #75, thanks @amedeedaboville!
