### ISSUE TITLE
suggested docs warning

### ISSUE THREAD

**Issue by jvanasco** [jsocol/pystatsd#77]
A common way to use Statsd is to create a client for a given process and continually reuse it.  That is fine, except for an annoying implementation detail that I noticed while securing a box.

When data is first sent via `socket` ( https://github.com/jsocol/pystatsd/blob/master/statsd/client.py#L145-L151 ) Python appears to bind on all interfaces (e.g. `0.0.0.0`) to a random port in effort of accepting a response.  (sidenote: it took a while to pinpoint this onto pystatsd).  It would make sense to note this inherent behavior in the docs/readme for the next person who is securing their box.

**Comment by jsocol** [comment]
Hmm, I don't suppose there's a way to stop it doing that?

**Comment by jvanasco** [comment]
Not that I could figure out when looking at python/socket's source; the behavior is basically undocumented and seems inherent.  Python binds once data is sent on the connection (but not once a connection is made).  I think it's just waiting for a response.  [To be honest, this drove me *&^*& crazy when trying to secure a linux box.]

With my naive understanding of networking, I don't think there is much a security concern like the recent glibc UDP issue (which is what I was testing against when I found this)... it's pretty much impossible to tell if a server is listening to UDP on any given port.   I did quickly prototype the client replacing the socket every `n` requests (1000?), and that brings back more of a random functionality.  That *might* be worth doing to offset the negligible chance of socket having a vulnerability one day.

**Comment by jsocol** [comment]
Fair enough, I think we can leave off that fix for now and deal with it if we need to in the future.

Any idea how or where to add it to the docs? Where would you have been likely to see it?

**Comment by jvanasco** [comment]
Maybe at the end of "Runtime" http://statsd.readthedocs.org/en/v3.2.1/configure.html just drop a note that says something like:

    Python will will inherently bind to an [ephemeral port ](https://en.wikipedia.org/wiki/Ephemeral_port) on all interfaces `0.0.0.0` for each configured client so it can accept UDP responses. It is safe to block this on your firewall if you wish.

**Comment by jvanasco** [comment]
I should add that I'm pretty sure this is for responses; it might also be for sending

**Comment by jsocol** [comment]
Done! Thanks @jvanasco
