### ISSUE TITLE
Mocking statsd object while running tests

### ISSUE THREAD

**Issue by prodicus** [jsocol/pystatsd#82]
Hey @jsocol 

Thanks for your detailed response on #81 . It worked for me using the context manager.

Now, I have a test suite in the project directory where I am using `statsd`. The method where I have my context manager is tested inside a unit test. 

Whenever I run `$ python setup.py test`, inside the statsd client, I see that the responses are getting logged in the statsd log (I am running statsd by doing a `$ node stats.js config.js 2>&1 > /tmp/statsd.log`)

```sh
27 Jun 07:07:24 - DEBUG: numStats: 4
27 Jun 07:07:32 - DEBUG: services.my_service-10.0.2.15-integrationtest#0_IOPerf:0.245810|ms
27 Jun 07:07:32 - DEBUG: services.my_service-10.0.2.15-integrationtest#0_IOPerf:0.254869|ms
27 Jun 07:07:34 - DEBUG: numStats: 5
27 Jun 07:07:34 - DEBUG: services.my_service-10.0.2.15-integrationtest#0_IOPerf:0.131845|ms
27 Jun 07:07:37 - DEBUG: services.test_IOPerf:0.015020|ms
27 Jun 07:07:37 - DEBUG: services.test_IOPerf:0.016212|ms
27 Jun 07:07:37 - DEBUG: services.test_IOPerf:0.015974|ms
27 Jun 07:07:37 - DEBUG: services.test_IOPerf:0.010967|ms
27 Jun 07:07:37 - DEBUG: services.test_IOPerf:0.011206|ms
27 Jun 07:07:37 - DEBUG: services.test_IOPerf:0.008821|ms
27 Jun 07:07:37 - DEBUG: services.test_IOPerf:0.010014|ms
....
....
```

Something like the above. Now I don't want this to happen. How would I `mock` my `statsd` object here so as to not cause this processor overhead while testing

**Method in which I have my `statsd` context manager, (which is being tested)**

```python
statsd = StatsClient(self.config['statsd_client'], prefix=socket.gethostname())
statsd_timer_name = '{0}_IOPerf'.format(self._consumer_tag)

with statsd.timer(statsd_timer_name):
      self.handle(json_message)
...
```

Any suggestions

**EDIT**: Minor changes

**Comment by jsocol** [comment]
I generally recommend setting the statsd host or port to a non-existent one for tests or local development, and not worrying about it. statsd is very fast and light, and uses UDP which is even faster and lighter.

As much as I'd like to, unfortunately I don't have time to answer application-specific questions. Something like StackOverflow is probably a better venue for things like this.

**Comment by prodicus** [comment]
Hey @jsocol 

I understand that. I achieved what I wanted after some time dabbling with my tests. Went through your source and saw that I have to override what was being returned by `timer()`

This worked in my case

```python
# inside the unit test
class A:
    def timer(self, *args):
        return MagicMock()

client.StatsClient = Mock(return_value=A())
```
I hope somebody finds it useful.

And thanks for your time and help @jsocol. Appreciate it :smile:

**Comment by LFED-FP** [comment]
@tasdikrahman Thanks for providing your solution, it helped me solve my testing problems! Cheers!
