### ISSUE TITLE
Question on additional exception handling in UDP client

### ISSUE THREAD

**Issue by nate-opti** [jsocol/pystatsd#84]
Wondering if you would be open to a PR adding additional exception handling, to catch *all* exceptions while attempting to send UDP stats, instead of just socket and `RuntimeError`s? In case, for example, `data.encode('ascii')` throws an error, but the user doesn't want to crash the application because of it.

E.g. changing this section: https://github.com/jsocol/pystatsd/blob/151ab6ba1d47a79404669b5a8c9b29d224862cf6/statsd/client.py#L145-L151

To this:
```
def _send(self, data):
    """Send data to statsd."""
    try:
        self._sock.sendto(data.encode('ascii'), self._addr)
    except Exception:
        # No time for love, Dr. Jones!
        pass
```

If not, this is certainly doable by the user of the lib, just wondering if you would like to add to trunk.

**Comment by jsocol** [comment]
Hmm, I don't love it because it's totally hidden—if you have metrics that don't work, you'd never know and your reporting would just be low.

**Comment by nate-opti** [comment]
Hmm yeah that's fair. Probably better for the user of the lib to catch whatever additional exceptions they expect / don't care about, and log them as warnings using whatever logger their application uses. Will do that. Thanks for the response!
