### ISSUE TITLE
Timer cannot decorate a partial function

### ISSUE THREAD

**Issue by leplatrem** [jsocol/pystatsd#85]
How to reproduce:

``` python
>>> import functools
>>> import time
>>> import statsd
>>> client = statsd.StatsClient()
>>> sleep5 = functools.partial(time.sleep, 5)
>>> client.timer('mystat')(sleep5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/statsd/client.py", line 26, in __call__
  File "/usr/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'functools.partial' object has no attribute '__module__'
```

There seems to be several approaches to fix it, like for example using a _safe_ version of `functools.wraps`. What do you think?
I would be happy to contribute a fix!

**Comment by jsocol** [comment]
Sorry, I think I missed this in my inbox. What is a "_safe_ version of `functools.wraps`? Is it in the stdlib?

**Comment by leplatrem** [comment]
It would be a decorator that would only wrap existing attributes.

https://stackoverflow.com/a/28752007/141895

**Comment by jsocol** [comment]
Ah cool, as long as it doesn't introduce new non-stdlib dependencies, I'm open to it!
