### ISSUE TITLE
Permission to add statsd to typeshed?

### ISSUE THREAD

**Issue by rowillia** [jsocol/pystatsd#87]
Howdy

I'd like to add stubs for statsd to https://github.com/python/typeshed, a repository used to store PEP 484 type signatures for the python stdlib and popular third party libraries. As per PEP 484, permission is required from the library owner before merging type signatures into typeshed - https://www.python.org/dev/peps/pep-0484/#the-typeshed-repo.  Would you mind if I contributed those stubs?

**Comment by jsocol** [comment]
What's going to be the ongoing expectation for maintaining the typeshed repo?

**Comment by rowillia** [comment]
@jsocol It will be by me.  We have been actively discussing how to best move these stubs to have their source of truth be in the repositories themselves, but for now it falls onto the folks maintaining typeshed itself.

Do you have a big refactor coming up?

**Comment by jsocol** [comment]
> Do you have a big refactor coming up?

No, but I would be pretty unwilling to accept ongoing responsibility for anything beyond the code, tests, and docs.

If typeshed will be doing the maintenance, it's fine by me, but at this point I'm not in a place to accept the maintenance here.
