### ISSUE TITLE
Statsd fails hard on gaierror

### ISSUE THREAD

**Issue by deejay1** [jsocol/pystatsd#91]
When there are temporary problems with DNS access decorating a function will result in an exception, which introduces unnecessary errors when for example it's used with RQ.

```python
    self._addr = (socket.gethostbyname(host), port)

gaierror: [Errno -2] Name or service not known
```

I think a better solution would be to either drop it or log it.

**Comment by jsocol** [comment]
Can you try on a more up-to-date version of the library? If it's still using `socket.gethostbyname` you're at least a few minor versions back (the change happened in dd7ce9169947e2a370a537700da2c4fae326204f).
