### ISSUE TITLE
Negative timer values due to time.time

### ISSUE THREAD

**Issue by Poogles** [jsocol/pystatsd#95]
We're seeing very occasional negative timer values due to NTP shifts and calls of time.time to gettimeofday(), rough background on that [here](https://blog.habets.se/2010/09/gettimeofday-should-never-be-used-to-measure-time.html).

[perf_counter](https://docs.python.org/3/library/time.html#time.perf_counter) provides the highest resolution wall time available in Python 3, fixing this for 2 seems a little harder.  [clock](https://docs.python.org/2/library/time.html#time.clock) seems to be the logical choice, it is also based off wall time, however it looks as though it suffers resolution problems according to the timeit docs [here](https://docs.python.org/2/library/timeit.html#timeit.default_timer).  Without wanting a resolution regression this bug/edgecase will likely have to stay.

Comparing the performance between time.time and time.perf_counter doesn't show any performance regression.

```
In [57]: timeit.timeit('perf_counter()', setup='from time import perf_counter', number=10000000)
Out[57]: 2.137723121792078

In [58]: timeit.timeit('time()', setup='from time import time', number=10000000)
Out[58]: 2.1814921628683805
```

I'll open a PR with a fix, I'm not sure how I'd write a test for this however.

**Comment by jsocol** [comment]
In terms of testing... I'm not sure. Mocking `time.time` isn't exactly a very interesting test if we're not using it, and I'm not about to start messing with real system clocks during a test suite.

I just merged it as-is and added a note to the changelog pointing to the issue/PR. Thanks!
