### ISSUE TITLE
with gevent

### ISSUE THREAD

**Issue by huangxiaohen2738** [jsocol/pystatsd#97]
when I use the celery with gevent, statsd doesn't work.

**Comment by jsocol** [comment]
Can you include more details? What kind of calls are you making? Does it work if you turn off gevent and use another process runner? Can you compare the traffic out of the process?

I've never had an issue using statsd and gevent in web app servers like Django or Flask, so it'd be interesting if there was something celery-specific about it.

**Comment by huangxiaohen2738** [comment]
I'm so sorry about it.
Because I use the pyroute2 to get the gateway addr.
